image: python:alpine

before_script:
  - pip3 install mkdocs
  - pip3 install python-markdown-math
  - pip3 install pymdown-extensions
  - pip3 install Pygments
  - pip3 install .

build:
  script:
    - mkdocs build
    - rm -rf /home/devuser/echo_web/public_wiki/*
    - cp -r ./public/* /home/devuser/echo_web/public_wiki/
  only:
    - master
  tags:
    - echo-linux
