image: python:alpine

before_script:
  - git pull origin master
  - pip3 install mkdocs
  - pip3 install pymdown-extensions
  - pip3 install .

build:
  script:
    - mkdocs build
    - cp -r ./public/* /home/devuser/echo_web/public_wiki/
  only:
    - master
  tags:
    - echo-linux
