site_name: ECHO Blockchain Wiki
site_url: https://wiki.myecho.app/
site_dir: public
theme:
    name: basictheme
    highlightjs: true
    hljs_languages:
      - javascript

markdown_extensions:
  - codehilite
  - toc:
      permalink: True
  - pymdownx.tasklist:

pages:
  - Introduction:
    - What is Echo?: introduction/what-is-echo.md
    # - How does Echo work?: introduction/how-does-echo-work.md
    - Whitepapers: introduction/whitepapers.md
  - Get started:
    - Installation:
      - Linux:  get-started/installation/linux.md
      - MacOS:  get-started/installation/macos.md
    - Running:
      - Node:  get-started/running/node.md
      - Wallet:  get-started/running/wallet.md
      - Docker:  get-started/running/docker.md
    # - Individuals: get-started/individuals.md
    # - Businisses:
    #   - Shops: get-started/Businisses/Shops.md
    #   - Exchange Platforms: get-started/Businisses/Exchange Platforms.md
    #   - Investors: get-started/Businisses/Investors.md
  - How To:
    - Use Echo: How To/Use Echo.md
    - Accept Echo: How To/Accept Echo.md
    - Issue Assets: How To/Issue Assets.md
    - Use Smart Contracts: How To/Use Smart Contracts.md
    - Issue Blocks/Get Rewarded: How To/Issue Blocks(Get Rewarded).md
    - Activate APIs:
      - RPC Call: How To/Activate APIs/RPC Call.md
      - Websocket API and Subscriptions: How To/Activate APIs/Websocket API and Subscriptions.md
    - Inspect Logs: How To/Inspect Logs.md
    - Report Issues: How To/Report Issues.md
  - Developers:
    - Smart Contracts:
      - Get Started: developers/smart-contracts/get-started.md
      - x86:
        - Create x86 Smart Contract: developers/smart-contracts/x86/Create x86 Smart Contract.md
        - Upload x86 Smart Contract: developers/smart-contracts/x86/Upload x86 Smart Contract.md
        - Application Interface (API): developers/smart-contracts/x86/Application Interface (API).md
        - Fees: developers/smart-contracts/x86/Fees.md
      - Solidity: developers/smart-contracts/solidity.md
#      - Tips & Tricks: developers/smart-contracts/Tips & Tricks.md
    - Command-Line Tools: developers/command-line-tools.md
    - Connect:
      - WebSocket API: developers/connect/websocket-api.md
      - Remote Procedure Call API: developers/connect/remote-procedure-call-api.md
      - Operations: developers/connect/operations.md
      - APIs: developers/connect/apis.md
    - Technologies:
      - Echorand: developers/Technologies/Echorand.md
      - Sidechain: developers/Technologies/Sidechain.md
      - Oracles: developers/Technologies/Oracles.md
      - Contracts/VMs: developers/Technologies/Contracts(VMs).md
    - Libraries and Frameworks:
      - EchoJS: developers/libraries-n-frameworks/echojs.md
      - Android and iOS: developers/libraries-n-frameworks/android-n-ios.md
    - Source Code:
      - Project structure: http://google.com
      - Build instructions: http://google.com

repo_url: https://github.com/d0ugal/mkdocs-basic-theme
