site_name: ECHO Blockchain Wiki
site_url: https://echo-de
site_dir: public
theme:
  name: basictheme
  highlightjs: true
  feature:
    tabs: true
  hljs_languages:
    - javascript

markdown_extensions:
  - codehilite
  - footnotes
  - attr_list
  - toc:
      permalink: True
      baselevel: 1
  - mdx_math
  - pymdownx.tasklist:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - Get started:
      - Installation: get-started/installation.md
      - Running Node and Cli-wallet: get-started/running.md
      - Running Committee Node: get-started/running-committee.md
      - Quickstart Docker: get-started/docker.md
  - How To:
      - Create account: how-to/create-account.md
      - Generate address: how-to/generate-address.md
      - Connect to blockchain:
          - Websocket API and Subscriptions: how-to/api/websocket-api-and-subscriptions.md
          - RPC Call: how-to/api/rpc-call.md
          - Cli-Wallet API: how-to/api/cli-wallet-api.md
          - API Access Restrictions: how-to/api/access.md
  - Developers:
      - APIs list: developers/apis.md
      - Smart Contracts:
          - Solidity:
              - Introduction: developers/smart-contracts/solidity/introduction.md
              - Hello World!: developers/smart-contracts/solidity/hello-world.md
              - Difference from ethereum: developers/smart-contracts/solidity/difference-from-ethereum.md
          - x86-64:
              - Introduction: developers/smart-contracts/x86-64/introduction.md
              - C++ Token contract: developers/smart-contracts/x86-64/cpp-contract.md
          - Smart Contract Fee Pool: developers/smart-contracts/fee-pool.md
      - Command-Line Tools: developers/command-line-tools.md
      - Operations: developers/operations.md
      - Libraries and Frameworks:
          - EchoJS: developers/libraries-n-frameworks/echojs.md
          - Android and iOS: developers/libraries-n-frameworks/android-n-ios.md
  - Technologies:
      - Echorand:
          - In a nutshell: technologies/echorand/in-a-nutshell.md
          - General View: technologies/echorand/overview.md
          - Architecture: technologies/echorand/architecture.md
          - Monitoring with ws: technologies/echorand/monitoring.md
      - Sidechains:
          - Bitcoin Sidechain: technologies/sidechain/bitcoin-sidechain-overview.md
          - Ethereum Sidechain: technologies/sidechain/ethereum-sidechain-overview.md
      - Echo x86-64 VM: technologies/echo-x86-64-vm.md

repo_url: https://github.com/d0ugal/mkdocs-basic-theme
